"""
embed_photos.py — PlatformIO pre-build script
Converts screensaver JPEGs into a C++ source + header so they can be
referenced as const arrays from flash (no SPIFFS partition required).

Reads from:
  assets/4inchScreensavers/Photo1.jpg … Photo3.jpg  (SCREEN_SIZE=4 builds)
  assets/7inchScreensavers/Photo1.jpg … Photo3.jpg  (SCREEN_SIZE=7 builds)

Writes:
  include/screensaver_photos.h
  src/screensaver_photos.cpp
"""

import os
Import("env")  # noqa: F821 — injected by PlatformIO

# ── Determine screen size from build flags ────────────────────────────────────
screen_size = "4"
for flag in env.get("BUILD_FLAGS", []):
    flag = str(flag)
    if "SCREEN_SIZE=7" in flag or "SCREEN_SIZE = 7" in flag:
        screen_size = "7"

print(f"[embed_photos] SCREEN_SIZE={screen_size} — embedding screensaver JPEGs")

proj_dir   = env["PROJECT_DIR"]
photo_dir  = os.path.join(proj_dir, f"assets/{screen_size}inchScreensavers")
out_h      = os.path.join(proj_dir, "include", "screensaver_photos.h")
out_cpp    = os.path.join(proj_dir, "src", "screensaver_photos.cpp")

# ── Generate header ───────────────────────────────────────────────────────────
with open(out_h, "w") as f:
    f.write("// AUTO-GENERATED by scripts/embed_photos.py — do not edit by hand\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n\n")
    for i in range(1, 4):
        f.write(f"extern const uint8_t  screensaver_photo_{i}[];\n")
        f.write(f"extern const uint32_t screensaver_photo_{i}_size;\n")
    f.write("\nextern const uint8_t*  const screensaver_photos[3];\n")
    f.write("extern const uint32_t        screensaver_photo_sizes[3];\n")

# ── Generate cpp ──────────────────────────────────────────────────────────────
# Minimal valid JPEG (2 bytes) used as fallback when a file is missing.
EMPTY_JPEG = bytes([0xFF, 0xD8, 0xFF, 0xD9])

with open(out_cpp, "w") as f:
    f.write("// AUTO-GENERATED by scripts/embed_photos.py — do not edit by hand\n")
    f.write('#include "screensaver_photos.h"\n\n')

    sizes = []
    for i in range(1, 4):
        path = os.path.join(photo_dir, f"Photo{i}.jpg")
        if os.path.exists(path):
            with open(path, "rb") as p:
                data = p.read()
            print(f"[embed_photos]   Photo{i}.jpg  {len(data):,} bytes")
        else:
            print(f"[embed_photos]   Photo{i}.jpg  NOT FOUND — using empty placeholder")
            data = EMPTY_JPEG

        sizes.append(len(data))
        f.write(f"const uint8_t screensaver_photo_{i}[] = {{\n")
        for j in range(0, len(data), 16):
            chunk = data[j:j+16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write(f"}};\n")
        f.write(f"const uint32_t screensaver_photo_{i}_size = {len(data)}UL;\n\n")

    f.write("const uint8_t* const screensaver_photos[3] = {\n")
    f.write("    screensaver_photo_1,\n")
    f.write("    screensaver_photo_2,\n")
    f.write("    screensaver_photo_3,\n")
    f.write("};\n\n")
    f.write("const uint32_t screensaver_photo_sizes[3] = {\n")
    for s in sizes:
        f.write(f"    {s}UL,\n")
    f.write("};\n")

print(f"[embed_photos] Written: include/screensaver_photos.h  src/screensaver_photos.cpp")
