"""
embed_favourites.py — PlatformIO pre-build script
Converts Quick Play favourite JPEG art + URI list into a C++ source + header
so tiles can be displayed from flash without network dependency.

Reads from (private takes priority, same pattern as embed_photos.py):
  assets/PrivateFavourites/favourites.txt  — 9 URIs, one per line
  assets/PrivateFavourites/fav1.jpg … fav9.jpg

  assets/DefaultFavourites/favourites.txt  — fallback (placeholder URIs)
  assets/DefaultFavourites/fav1.jpg … fav9.jpg

Writes:
  include/favourites_data.h
  src/favourites_data.cpp
"""

import os
Import("env")  # noqa: F821 — injected by PlatformIO

print("[embed_favourites] Embedding Quick Play favourites")

proj_dir    = env["PROJECT_DIR"]
private_dir = os.path.join(proj_dir, "assets/PrivateFavourites")
public_dir  = os.path.join(proj_dir, "assets/DefaultFavourites")

if os.path.isdir(private_dir):
    fav_dir = private_dir
    print(f"[embed_favourites] Using PRIVATE favourites from {private_dir}")
else:
    fav_dir = public_dir
    print(f"[embed_favourites] Using default favourites from {public_dir}")

out_h   = os.path.join(proj_dir, "include", "favourites_data.h")
out_cpp = os.path.join(proj_dir, "src",     "favourites_data.cpp")

NUM_FAVS = 12

# ── Read URIs ─────────────────────────────────────────────────────────────────
uri_file = os.path.join(fav_dir, "favourites.txt")
uris = []
if os.path.isfile(uri_file):
    with open(uri_file) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                uris.append(line)
uris = (uris + [""] * NUM_FAVS)[:NUM_FAVS]  # pad / trim to exactly NUM_FAVS

# ── Minimal valid JPEG fallback ───────────────────────────────────────────────
EMPTY_JPEG = bytes([0xFF, 0xD8, 0xFF, 0xD9])

# ── Generate header ───────────────────────────────────────────────────────────
with open(out_h, "w") as f:
    f.write("// AUTO-GENERATED by scripts/embed_favourites.py — do not edit\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n\n")
    f.write(f"#define NUM_FAVOURITES {NUM_FAVS}\n\n")
    for i in range(1, NUM_FAVS + 1):
        f.write(f"extern const uint8_t  fav_art_{i}[];\n")
        f.write(f"extern const uint32_t fav_art_{i}_size;\n")
    f.write("\nextern const uint8_t*  const fav_art[NUM_FAVOURITES];\n")
    f.write("extern const uint32_t        fav_art_sizes[NUM_FAVOURITES];\n")
    f.write("extern const char*     const fav_uris[NUM_FAVOURITES];\n")

# ── Generate cpp ──────────────────────────────────────────────────────────────
with open(out_cpp, "w") as f:
    f.write("// AUTO-GENERATED by scripts/embed_favourites.py — do not edit\n")
    f.write('#include "favourites_data.h"\n\n')

    sizes = []
    for i in range(1, NUM_FAVS + 1):
        jpg_path = os.path.join(fav_dir, f"fav{i}.jpg")
        if os.path.isfile(jpg_path):
            data = open(jpg_path, "rb").read()
            print(f"[embed_favourites]   fav{i}.jpg — {len(data)} bytes")
        else:
            data = EMPTY_JPEG
            print(f"[embed_favourites]   fav{i}.jpg — MISSING, using empty JPEG placeholder")

        sizes.append(len(data))
        f.write(f"const uint8_t fav_art_{i}[] = {{")
        f.write(", ".join(f"0x{b:02X}" for b in data))
        f.write(f"}};\n")
        f.write(f"const uint32_t fav_art_{i}_size = {len(data)};\n\n")

    # Pointer arrays
    f.write("const uint8_t* const fav_art[NUM_FAVOURITES] = {\n")
    f.write("    " + ", ".join(f"fav_art_{i}" for i in range(1, NUM_FAVS + 1)) + "\n};\n\n")

    f.write("const uint32_t fav_art_sizes[NUM_FAVOURITES] = {\n")
    f.write("    " + ", ".join(str(s) for s in sizes) + "\n};\n\n")

    # URI strings
    f.write("const char* const fav_uris[NUM_FAVOURITES] = {\n")
    for uri in uris:
        escaped = uri.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    "{escaped}",\n')
    f.write("};\n")
