// AUTO-GENERATED by scripts/embed_favourites.py — do not edit
#pragma once
#include <stdint.h>

#define NUM_FAVOURITES 12

extern const uint8_t  fav_art_1[];
extern const uint32_t fav_art_1_size;
extern const uint8_t  fav_art_2[];
extern const uint32_t fav_art_2_size;
extern const uint8_t  fav_art_3[];
extern const uint32_t fav_art_3_size;
extern const uint8_t  fav_art_4[];
extern const uint32_t fav_art_4_size;
extern const uint8_t  fav_art_5[];
extern const uint32_t fav_art_5_size;
extern const uint8_t  fav_art_6[];
extern const uint32_t fav_art_6_size;
extern const uint8_t  fav_art_7[];
extern const uint32_t fav_art_7_size;
extern const uint8_t  fav_art_8[];
extern const uint32_t fav_art_8_size;
extern const uint8_t  fav_art_9[];
extern const uint32_t fav_art_9_size;
extern const uint8_t  fav_art_10[];
extern const uint32_t fav_art_10_size;
extern const uint8_t  fav_art_11[];
extern const uint32_t fav_art_11_size;
extern const uint8_t  fav_art_12[];
extern const uint32_t fav_art_12_size;

extern const uint8_t*  const fav_art[NUM_FAVOURITES];
extern const uint32_t        fav_art_sizes[NUM_FAVOURITES];
extern const char*     const fav_uris[NUM_FAVOURITES];
