// AUTO-GENERATED by scripts/embed_photos.py — do not edit by hand
#pragma once
#include <stdint.h>

extern const uint8_t  screensaver_photo_1[];
extern const uint32_t screensaver_photo_1_size;
extern const uint8_t  screensaver_photo_2[];
extern const uint32_t screensaver_photo_2_size;
extern const uint8_t  screensaver_photo_3[];
extern const uint32_t screensaver_photo_3_size;

extern const uint8_t*  const screensaver_photos[3];
extern const uint32_t        screensaver_photo_sizes[3];
